version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    image: andrerampanelli1/app-node:dev
    container_name: app-dev
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    tty: true
    volumes: 
      - ./app:/usr/src/app
    networks: 
      - nginx-node
    depends_on: 
      - db
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./.mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-node

networks: 
  nginx-node:
    driver: bridge  