version: "3.8"

services:
  app:
    build:
      context: ./app
    image: andrerampanelli1/app-node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks: 
      - nginx-node
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./.mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-node

  nginx:
    restart: always
    build:
      context: ./nginx
    image: andrerampanelli1/nginx-app
    container_name: nginx
    networks: 
      - nginx-node
    ports:
      - "8080:80"

networks: 
  nginx-node:
    driver: bridge  